/**
 * BullMQ Worker — Email Delivery
 *
 * Handles individual certificate email delivery jobs. Each email is processed
 * independently so that a single failure doesn't block the entire batch.
 *
 * This replaces the inline email sending that previously happened inside the
 * certificate generation loop (tight coupling) and the sync loop in
 * `/jobs/:id/resend-emails`.
 *
 * Benefits:
 *   - Failed emails are automatically retried (5 attempts, exponential backoff)
 *   - Email sending doesn't slow down PDF generation
 *   - Rate limiting is naturally handled by BullMQ concurrency + limiter
 *   - Individual email status tracked per-record
 */
const fs = require('fs');
const { Worker } = require('bullmq');
const { createRedisConnection } = require('../config/redis');
const { getDB } = require('../config/db');
const { deliverCertificate } = require('../services/certificateEmailService');
const storageService = require('../services/storageService');

const now = () => new Date().toISOString();

/**
 * Process a single email delivery job.
 *
 * @param {import('bullmq').Job} job
 * @param {object} job.data
 * @param {string} job.data.certId        — Certificate ID
 * @param {string} job.data.organizationId — Organization ID for scoping
 * @param {string} job.data.recordId       — Bulk record ID (if from bulk)
 * @param {string} job.data.jobId          — Bulk job ID (if from bulk)
 * @param {object} [job.data.templateSnapshot] — Template data (optional, fetched if missing)
 * @param {string} [job.data.pdfPath]      — Path to generated PDF
 */
async function processEmailJob(job) {
  const { certId, organizationId, recordId, jobId, templateSnapshot, pdfPath } = job.data;
  const db = getDB();

  // Fetch the certificate
  const cert = await db.collection('certificates').findOne({
    cert_id: certId,
    organization_id: organizationId
  });

  if (!cert) throw new Error(`Certificate ${certId} not found`);
  if (!cert.recipient_email) {
    // No email to send — mark as skipped
    await updateEmailStatus(db, cert, recordId, 'skipped', null);
    return { status: 'skipped', reason: 'no_email' };
  }

  // Already sent — idempotent
  if (cert.email_status === 'sent' && cert.sent_email) {
    return { status: 'already_sent', certId };
  }

  // Get template
  let template = templateSnapshot;
  if (!template) {
    template = await db.collection('templates').findOne({ id: cert.template_id });
  }

  // Get PDF buffer
  let pdfBuffer = null;
  if (pdfPath) {
    try {
      pdfBuffer = await storageService.getPdfBuffer(pdfPath);
    } catch {
      // PDF not found — renderer will generate it
    }
  } else if (cert.pdf_path) {
    try {
      pdfBuffer = await storageService.getPdfBuffer(cert.pdf_path);
    } catch {
      // Will be generated by deliverCertificate
    }
  }

  // Deliver
  const result = await deliverCertificate({ cert, template, pdfBuffer });

  const emailStatus = result.delivered ? 'sent' : 'failed';
  await updateEmailStatus(db, cert, recordId, emailStatus, result);

  if (!result.delivered) {
    throw new Error(`Email delivery failed for ${certId}: ${result.error || 'Unknown error'}`);
  }

  return {
    status: 'sent',
    certId,
    emailId: result.email_id
  };
}

/**
 * Update email status in both certificates and bulk_records collections.
 */
async function updateEmailStatus(db, cert, recordId, emailStatus, result) {
  const emailPatch = {
    sent_email: emailStatus === 'sent',
    email_status: emailStatus,
    email_id: result?.email_id || null,
    email_actual_recipient: result?.actual_recipients?.[0] || null,
    email_error: emailStatus === 'sent' ? null : (result?.error || 'Email delivery failed'),
    email_sent_at: emailStatus === 'sent' ? now() : null
  };

  // Update certificate
  await db.collection('certificates').updateOne(
    { cert_id: cert.cert_id, organization_id: cert.organization_id },
    { $set: emailPatch }
  );

  // Update bulk record if applicable
  if (recordId) {
    await db.collection('bulk_records').updateOne(
      { _id: recordId, organization_id: cert.organization_id },
      {
        $set: {
          email_status: emailStatus,
          email_id: result?.email_id || null,
          email_error: emailStatus === 'sent' ? null : 'Email delivery failed'
        }
      }
    );
  }
}

/** @type {Worker | null} */
let worker = null;

/**
 * Start the BullMQ email delivery worker.
 *
 * @param {object} [opts] - Override worker options
 * @returns {Worker}
 */
function startEmailWorker(opts = {}) {
  if (worker) return worker;

  const connection = createRedisConnection();

  worker = new Worker(
    'email-delivery',
    processEmailJob,
    {
      connection,
      concurrency: 5,         // Max 5 concurrent email sends
      lockDuration: 30000,     // 30s lock per email
      stalledInterval: 15000,
      maxStalledCount: 1,
      limiter: {
        max: 50,               // Max 50 emails per minute (Resend free tier friendly)
        duration: 60000
      },
      ...opts
    }
  );

  worker.on('completed', (job, result) => {
    if (result?.status !== 'already_sent' && result?.status !== 'skipped') {
      console.log(`[EmailWorker] Email sent for cert ${job.data.certId}`);
    }
  });

  worker.on('failed', (job, error) => {
    console.error(`[EmailWorker] Email failed for cert ${job?.data?.certId}:`, error.message);
  });

  worker.on('error', (error) => {
    console.error('[EmailWorker] Worker error:', error.message);
  });

  console.log('[EmailWorker] Started with concurrency=5, rate=50/min');
  return worker;
}

/**
 * Gracefully stop the email worker.
 */
async function stopEmailWorker() {
  if (worker) {
    await worker.close();
    worker = null;
    console.log('[EmailWorker] Stopped');
  }
}

module.exports = { startEmailWorker, stopEmailWorker, processEmailJob };
